cd root
./vision.elf /my_shared_memory
/my_shared_memory
/my_shared_memory
./vision.elf /my_shared_memory
md5sum files/95
./vision.elf /my_shared_memory
md5sum files/95
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
./vision.elf /my_shared_memory
quit
exit
